config/routes.rb
Rails.application.routes.draw do
  resources :emails
  resources :bulk_upload_requests do
    collection do 
      get 'configurations'
    end
  end
  root 'companies#index'
  resources :companies do
    member do
      get 'configuration'
    end
  end
  devise_for :users
  root 'profiles#index'  
  resources :profiles
  resources :company_configurations

end

app/models/profile.rb
require 'bulk_upload_setting.rb'
include ExcelReader

class Profile < ApplicationRecord

  # *********************MIXINS START*******************************************
  include BulkUploadSetting
  # *********************MIXINS END********************************************
  
  belongs_to :company
  validates_presence_of :first_name, :email
  validates_format_of :email,:with => Devise::email_regexp 
  # *********************CONSTANT DEFINITION START***********************************
  # sll - Secondary Landline number
  #bm - Birth Mark
  JSON_ACCESSORS = [:sll, :bm]
  store_accessor :json_store, *JSON_ACCESSORS
  # *********************CONSTANT DEFINITION END*************************************

  # *********************TRIGGER DEFINITION START************************************
  after_initialize :init
  # *********************TRIGGER DEFINITON END***************************************

  # *********************TRIGGER METHOD DEFINITION START*****************************
  def init
    self.sll ||= ""
    self.bm ||= ""
  rescue ActiveModel::MissingAttributeError
    # This happens on Model.select calls when these attributes might not be loaded. It can be safely ignored.  
  end
  # *********************TRIGGER METHOD DEFINITION END*******************************

  def self.handle_bulk_upload(data, options={})
    Profile.initiate_bulk_upload(data, options={})
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    # @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
    # @model_type = 'profile'
    # Profile fields default for all companies
    @form_fields = @profile.basic_facts_fields['profile']
    # Override form fields for company specific BasicSettings

  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new
    @form_fields = @profile.basic_facts_fields['profile']
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to new_profile_path, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, alert: 'Some Error Occurred!' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :email, :blood_group, :sll, :bm, :company_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.haml
/ = render partial: 'companies/partials/basic_dynamic_form', locals: {model_type: @model_type, form_fields: @form_fields}
- if @profile.errors.any?
  #error_explanation
    %h2
      = pluralize(@profile.errors.count, "error") + " prohibited this user from being saved:"
    %ul 
      - @profile.errors.full_messages.each do |msg|
        %li
          = msg
= form_for @profile, :builder => ApplicationHelper::MarkedFormBuilder do |f|
  = f.hidden_field :company_id, value: '1'
  .slight-top-margin
    = f.marked_label :first_name, @form_fields.fetch('first_name', 'First Name')
    = f.text_field :first_name
  %br/
  .slight-top-margin
    = f.marked_label :last_name, @form_fields.fetch('last_name', 'Last Name')
    = f.text_field :last_name
  %br/
  .slight-top-margin
    = f.marked_label :email, @form_fields.fetch('email', 'Email')
    = f.text_field :email
  %br/
  .slight-top-margin
    = f.marked_label :blood_group, @form_fields.fetch('blood_group', 'Blood Group')
    = f.text_field :blood_group
  %br/
  .slight-top-margin
    = f.marked_label :sll, @form_fields.fetch('sll', 'Secondary Landline')
    = f.text_field :sll
  %br/
  .slight-top-margin
    = f.marked_label :bm, @form_fields.fetch('bm', 'Birth Mark')
    = f.text_field :bm
  %br/
  .slight-top-margin
    = f.submit 'Save'

app/views/profiles/edit.html.haml
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.haml
<p id="notice"><%= notice %></p>

<h1 class="slight-top-margin">Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Blood group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.email %></td>
        <td><%= profile.blood_group %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.haml
%h1.slight-top-margin
  New Profile
= render 'form', locals: {profile: @profile, model_type: @model_type, form_fields: @form_fields}

app/views/profiles/show.html.haml
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile.email %>
</p>

<p>
  <strong>Blood group:</strong>
  <%= @profile.blood_group %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>