config/routes.rb
Rails.application.routes.draw do
  resources :emails
  resources :bulk_upload_requests do
    collection do 
      get 'configurations'
    end
  end
  root 'companies#index'
  resources :companies do
    member do
      get 'configuration'
    end
  end
  devise_for :users
  root 'profiles#index'  
  resources :profiles
  resources :company_configurations

end

app/models/company.rb
class Company < ApplicationRecord


  # *********************RELATIONSHIP DEFINITION START*******************************
  belongs_to :configuration, class_name: "CompanyConfiguration", foreign_key: :cc_id  
  has_many :profiles
  # *********************RELATIONSHIP DEFINITION END*********************************

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def configuration
    @company = Company.find(params[:id])
    @configuration = @company.configuration
    @bulk_upload_default_model_fields = @configuration.bulk_upload_default_fields
    # For Nested Models and polymorphic models
    # @bulk_upload_default_model_nested_fields = @configuration.bulk_upload_default_nested_fields 

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :registered_name, :email)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_bu_default_model_fields.html.haml
.row
  - bulk_upload_default_model_fields.each.with_index(1) do |(model, model_attributes), index|
    #accordion.panel-group
      .slight-top-margin.panel.panel-primary
        .panel-heading
          .panel-title
            %a{ "data-toggle" => "collapse", "data-parent" => "#accordion", :href => '#'+"#{model}"+'_setting_form' }
              #{model} Bulk Upload Settings
              .pull-right.btn.btn-xs.btn-success
                Show
    .panel-collapse.collapse{id: "#{model}"+'_setting_form'}
      .panel-body
        = form_for configuration, html: {class: "bu_settings" ,id: "#{model}"+'_bu_settings', data: {"conf": "#{model}"}} do |cc|
          = hidden_field_tag :scope, "#{model}_bu_headers_sequence"
          = hidden_field_tag :company_id, company.id if company.present?
          .slight-top-margin
            = label_tag 'Select All'
            = check_box_tag "#{model}"+'_select_all', nil, false,  class: "#{model}_select_all select_all", id: "#{model}_select_all", data: {conf:"#{model}"}
            .row
              - model_attributes.each do |field, label|
                .col-md-2
                  .label-card.checkbox-inline.slight-top-margin
                    = check_box_tag "#{model}_bu_headers_sequence[#{field}]", configuration.send("#{model}_bu_headers_sequence")[field], cc.object.send("#{model}_bu_headers_sequence").keys.include?(field.to_s), class: "selectable #{model}_selectable #{model}_sortable_checkbox sortable_checkbox", data: {list_id:"#{model}_list_fields", conf:"#{model}"}
                    = label_tag field
              .col-md-10.field.slight-top-margin
                %table.drag_drop{class: "#{model}_list_fields #{model}_drag_drop", data: {"conf": "#{model}"}}
                  %thead
                    %span.bold #{model} List (sortable)
                  %tbody.ui-sortable{data: {"conf": "#{model}"}}
                    - unless configuration.send("#{model}_bu_headers_sequence").blank?
                      - configuration.send("#{model}_bu_headers_sequence").each.with_index(1) do |(header, sequence), index|
                        - index = index.to_s
                        - unless configuration.send("#{model}_bu_headers_sequence").key(index).blank?
                          %tr{class: "#{model}_field_tr"}
                            %td.priority
                              = index
                            %td{id: "#{model}_bu_headers_sequence_#{header}"}
                              = configuration.send("#{model}_bu_headers_sequence").key(index).humanize
                  }
          = cc.submit "Save", class: "btn btn-danger"

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :registered_name %>
    <%= form.text_field :registered_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/_form.html.haml
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :registered_name %>
    <%= form.text_field :registered_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/configuration.html.haml
%h3.slight-top-margin
  #{@company.name} Configuration Page
%br/

= render partial: "companies/bu_default_model_fields", locals: {company: @company, configuration: @configuration, bulk_upload_default_model_fields: @bulk_upload_default_model_fields}

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/edit.html.haml
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class='slight-top-margin'>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Registered name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.registered_name %></td>
        <td><%= company.email %></td>
        <td><%= link_to 'Configuration', configuration_company_path(company), target: '_blank'%></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/index.html.haml
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Registered name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.registered_name %></td>
        <td><%= company.email %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/new.html.haml
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Registered name:</strong>
  <%= @company.registered_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @company.email %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/companies/show.html.haml
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Registered name:</strong>
  <%= @company.registered_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @company.email %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>