config/routes.rb
Rails.application.routes.draw do
  resources :emails
  resources :bulk_upload_requests do
    collection do 
      get 'configurations'
    end
  end
  root 'companies#index'
  resources :companies do
    member do
      get 'configuration'
    end
  end
  devise_for :users
  root 'profiles#index'  
  resources :profiles
  resources :company_configurations

end

app/models/bulk_upload_request.rb
require 'bulk_upload_setting.rb'
class BulkUploadRequest < ApplicationRecord
  include BulkUploadSetting

  def specific_model_default_fields(model_type)
    self.bulk_upload_default_fields.slice(model_type)    
  end

end

app/controllers/bulk_upload_requests_controller.rb
class BulkUploadRequestsController < ApplicationController
  before_action :set_bulk_upload_request, only: [:show, :edit, :update, :destroy]

  # GET /bulk_upload_requests
  # GET /bulk_upload_requests.json
  def index
    @bulk_upload_requests = BulkUploadRequest.all
  end

  # GET /bulk_upload_requests/1
  # GET /bulk_upload_requests/1.json
  def show
  end

  # GET /bulk_upload_requests/new
  def new
    @bulk_upload_request = BulkUploadRequest.new
    @companies = Company.all
    @model_names = @bulk_upload_request.bulk_upload_default_fields.keys
  end

  # GET /bulk_upload_requests/1/edit
  def edit
  end

  # POST /bulk_upload_requests
  # POST /bulk_upload_requests.json
  def create
    # debugger
    company = Company.find_by_id(params[:company_id])
    @bulk_upload_request = BulkUploadRequest.new(bulk_upload_request_params)
    if !params[:model_name].blank?
      klass = model_object = params[:model_name].classify.constantize
      klass.handle_bulk_upload(params, {company_id: params[:company_id], model_name: params[:model_name]})
    end
    respond_to do |format|
      if @bulk_upload_request.save
        format.html { redirect_to @bulk_upload_request, notice: 'Bulk upload request was successfully created.' }
        format.json { render :show, status: :created, location: @bulk_upload_request }
      else
        format.html { render :new }
        format.json { render json: @bulk_upload_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bulk_upload_requests/1
  # PATCH/PUT /bulk_upload_requests/1.json
  def update
    respond_to do |format|
      if @bulk_upload_request.update(bulk_upload_request_params)
        format.html { redirect_to @bulk_upload_request, notice: 'Bulk upload request was successfully updated.' }
        format.json { render :show, status: :ok, location: @bulk_upload_request }
      else
        format.html { render :edit }
        format.json { render json: @bulk_upload_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bulk_upload_requests/1
  # DELETE /bulk_upload_requests/1.json
  def destroy
    @bulk_upload_request.destroy
    respond_to do |format|
      format.html { redirect_to bulk_upload_requests_url, notice: 'Bulk upload request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def configurations
    @bulk_upload_request = BulkUploadRequest.new
    @company = Company.find_by_id(params[:company_id])
    @configuration = @company.configuration if !@company.blank?
    selected_model = params[:model_type]
    @bulk_upload_default_model_fields = @bulk_upload_request.specific_model_default_fields(selected_model)
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bulk_upload_request
      @bulk_upload_request = BulkUploadRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bulk_upload_request_params
      params.permit(:bulk_upload_request, :json_store)
    end
end

app/helpers/bulk_upload_requests_helper.rb
module BulkUploadRequestsHelper
end

app/views/bulk_upload_requests/_form.html.haml
= form_for @bulk_upload_request, html: {multipart: true} do |f|
  .slight-top-margin
    = label_tag "Choose Company"
    = select_tag :company_id, options_from_collection_for_select(@companies, :id, :name)
  %br/
  .slight-top-margin
    = label_tag "Choose Functionality"
    = select_tag :model_name, options_for_select(@model_names, "report")
  #configuration
  #spreadsheet.block_spreadsheet.cal
  .slight-top-margin
    #progressbar.hidden
      .progress-label
    = label_tag 'Excel sheet',nil, class: 'excel_sheet'
    = file_field_tag :bulk_upload, accept:".xlsx"
    %br/
    = submit_tag "Submit and Send Email" , id: 'submit_bulk_upload_excel'

    .after_completion_actions.cal.hidden
      %f14 Do you want to upload more?
      = link_to "Yes", new_bulk_upload_request_path, method: :get
      = link_to "No", root_url, method: :get

app/views/bulk_upload_requests/configurations.js.haml
:plain
  $("#configuration").html("#{escape_javascript(render :partial => "companies/bu_default_model_fields", locals: {company: @company, configuration: @company.configuration, bulk_upload_default_model_fields: @bulk_upload_default_model_fields})}");

app/views/bulk_upload_requests/edit.html.haml
<h1>Editing Bulk Upload Request</h1>

<%= render 'form', bulk_upload_request: @bulk_upload_request %>

<%= link_to 'Show', @bulk_upload_request %> |
<%= link_to 'Back', bulk_upload_requests_path %>

app/views/bulk_upload_requests/index.html.haml
<p id="notice"><%= notice %></p>

<h1>Bulk Upload Requests</h1>

<table>
  <thead>
    <tr>
      <th>Json store</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bulk_upload_requests.each do |bulk_upload_request| %>
      <tr>
        <td><%= bulk_upload_request.json_store %></td>
        <td><%= link_to 'Show', bulk_upload_request %></td>
        <td><%= link_to 'Edit', edit_bulk_upload_request_path(bulk_upload_request) %></td>
        <td><%= link_to 'Destroy', bulk_upload_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bulk Upload Request', new_bulk_upload_request_path %>

app/views/bulk_upload_requests/new.html.haml
%h1.slight-top-margin 
  New Bulk Upload Request

= render 'form', bulk_upload_request: @bulk_upload_request

= link_to 'Back', bulk_upload_requests_path

app/views/bulk_upload_requests/show.html.haml
%p.slight-top-margin
  #notice
    = notice

%h1.slight-top-margin
  Json store:
  %br/
  = @bulk_upload_request.json_store

%br/
= link_to 'Edit', edit_bulk_upload_request_path(@bulk_upload_request)
%br/
= link_to 'Back', bulk_upload_requests_path